name: CI/CD Frontend Vue

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build and Push a ECR
        run: |
          docker build -t ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest .
          docker push ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

      - name: Desplegar Frontend vía SSM
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ secrets.EC2_FRONTEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters '{
              "commands":[
                "set -e",
                "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
                "docker pull ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest",
                "docker stop frontend-vue || true",
                "docker rm frontend-vue || true",
                "docker run -d --name frontend-vue -p 80:80 ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest"
              ]
            }' \
            --query "Command.CommandId" \
            --output text)
            
          echo "Comando enviado: $COMMAND_ID"
          aws ssm wait command-executed --command-id "$COMMAND_ID" --instance-id ${{ secrets.EC2_FRONTEND_INSTANCE_ID }}